NCEPLIBS-g2: pngpack.F90 File Reference
pngpack.F90 File Reference
This subroutine packs up a data field into PNG image format.
Functions/Subroutines
subroutine pngpack (fld, width, height, idrstmpl, cpack, lcpack)
This subroutine packs up a data field into PNG image format.
Detailed Description
This subroutine packs up a data field into PNG image format.
Author
Stephen Gilbert
Date
2002-12-21
Definition in file pngpack.F90.
Function/Subroutine Documentation
pngpack()
subroutine pngpack (real, dimension(width * height), intent(in) fld, integer, intent(in) width, integer, intent(in) height, integer, dimension(*), intent(inout) idrstmpl, character(len = 1), dimension(*), intent(out) cpack, integer, intent(out) lcpack)
This subroutine packs up a data field into PNG image format.
After the data field is scaled, and the reference value is subtracted out, it is treated as a grayscale image and passed to a PNG encoder. It also fills in GRIB2 Data Representation Template 5.41 or 5.40010 with the appropriate values.
Parameters
[in] fld Contains the data values to pack.
[in] width number of points in the x direction.
[in] height number of points in the y direction.
[in,out] idrstmpl Contains the array of values for Data Representation Template 5.2 or 5.3.
idrstmpl(1) Reference value - ignored on input.
idrstmpl(2) Binary Scale Factor.
idrstmpl(3) Decimal Scale Factor.
idrstmpl(4) Number of bits containing each grayscale pixel value.
idrstmpl(5) Original field type, currently set = 0 on output Data values assumed to be reals.
idrstmpl(6) = 0 use lossless compression; = 1 use lossy compression.
idrstmpl(7) Desired compression ratio, if idrstmpl(6)=1.
[out] cpack The packed data field (character*1 array)
[out] lcpack The length of packed field cpack.
Author
Stephen Gilbert
Date
2002-12-21
Definition at line 28 of file pngpack.F90.
References enc_png(), g2_sbytesc(), and mkieee().
Referenced by addfield().