NCEPLIBS-g2: intmath Module Reference
intmath Module Reference
This module defines integer math functions used by other programs.
Data Types
interface i1log2
interface ilog2
Public Member Functions
integer(kind=1) function i1log2_1 (ival)
This function returns log(x+1)/log(2) unless x=maxint, in which case log(x)/log(2) for 1 bit integer numbers.
integer(kind=2) function i1log2_2 (ival)
This function returns log(x+1)/log(2) unless x=maxint, in which case log(x)/log(2) for 2 bit integer numbers.
integer(kind=4) function i1log2_4 (ival)
This function returns log(x+1)/log(2) unless x=maxint, in which case log(x)/log(2) for 4 bit integer numbers.
integer(kind=8) function i1log2_8 (ival)
This function returns log(x+1)/log(2) unless x=maxint, in which case log(x)/log(2) for 8 bit integer numbers.
integer(kind=1) function ilog2_1 (i_in)
This function returns log(x)/log(2) for 1 bit integer numbers.
integer(kind=2) function ilog2_2 (i_in)
This function returns log(x)/log(2) for 2 bit integer numbers.
integer(kind=4) function ilog2_4 (i_in)
This function returns log(x)/log(2) for 4 bit integer numbers.
integer(kind=8) function ilog2_8 (i_in)
This function returns log(x)/log(2) for 8 bit integer numbers.
Detailed Description
This module defines integer math functions used by other programs.
It include following functions:
ilog2 Calculate log(x)/log(2).
ilog2_8 for 8 bit integer numbers.
ilog2_4 for 4 bit integer numbers.
ilog2_2 for 2 bit integer numbers.
ilog2_1 for 1 bit integer numbers.
i1log2 Calculate log(x+1)/log(2) unless x=maxint, in which case log(x)/log(2).
i1log2_8 for 8 bit integer numbers.
i1log2_4 for 4 bit integer numbers.
i1log2_2 for 2 bit integer numbers.
i1log2_1 for 1 bit integer numbers.
Author
Stephen Gilbert
Date
2000-06-21
Definition at line 22 of file intmath.f.
Member Function/Subroutine Documentation
integer(kind=1) function intmath::i1log2_1 (integer(kind=1) ival)
This function returns log(x+1)/log(2) unless x=maxint, in which case log(x)/log(2) for 1 bit integer numbers.
Parameters
[in] ival 1 bit integer numbers.
Returns
value for log(x+1)/log(2)
Author
Stephen Gilbert
Date
2000-06-21
Definition at line 115 of file intmath.f.
References intmath::i1log2::i1log2_1(), and intmath::ilog2::ilog2_1().
integer(kind=2) function intmath::i1log2_2 (integer(kind=2) ival)
This function returns log(x+1)/log(2) unless x=maxint, in which case log(x)/log(2) for 2 bit integer numbers.
Parameters
[in] ival 2 bit integer numbers.
Returns
value for log(x+1)/log(2)
Author
Stephen Gilbert
Date
2000-06-21
Definition at line 94 of file intmath.f.
References intmath::i1log2::i1log2_2(), and intmath::ilog2::ilog2_2().
integer(kind=4) function intmath::i1log2_4 (integer(kind=4) ival)
This function returns log(x+1)/log(2) unless x=maxint, in which case log(x)/log(2) for 4 bit integer numbers.
Parameters
[in] ival 4 bit integer numbers.
Returns
value for log(x+1)/log(2)
Author
Stephen Gilbert
Date
2000-06-21
Definition at line 73 of file intmath.f.
References intmath::i1log2::i1log2_4(), and intmath::ilog2::ilog2_4().
integer(kind=8) function intmath::i1log2_8 (integer(kind=8) ival)
This function returns log(x+1)/log(2) unless x=maxint, in which case log(x)/log(2) for 8 bit integer numbers.
Parameters
[in] ival 8 bit integer numbers.
Returns
value for log(x+1)/log(2)
Author
Stephen Gilbert
Date
2000-06-21
Definition at line 52 of file intmath.f.
References intmath::i1log2::i1log2_8(), and intmath::ilog2::ilog2_8().
integer(kind=1) function intmath::ilog2_1 (integer(kind=1) i_in)
This function returns log(x)/log(2) for 1 bit integer numbers.
Parameters
[in] i_in 1 bit integer numbers.
Returns
value for log(x)/log(2)
Author
Stephen Gilbert
Date
2000-06-21
Definition at line 273 of file intmath.f.
References intmath::ilog2::ilog2_1().
integer(kind=2) function intmath::ilog2_2 (integer(kind=2) i_in)
This function returns log(x)/log(2) for 2 bit integer numbers.
Parameters
[in] i_in 2 bit integer numbers.
Returns
value for log(x)/log(2)
Author
Stephen Gilbert
Date
2000-06-21
Definition at line 232 of file intmath.f.
References intmath::ilog2::ilog2_2().
integer(kind=4) function intmath::ilog2_4 (integer(kind=4) i_in)
This function returns log(x)/log(2) for 4 bit integer numbers.
Parameters
[in] i_in 4 bit integer numbers.
Returns
value for log(x)/log(2)
Author
Stephen Gilbert
Date
2000-06-21
Definition at line 186 of file intmath.f.
References intmath::ilog2::ilog2_4().
integer(kind=8) function intmath::ilog2_8 (integer(kind=8) i_in)
This function returns log(x)/log(2) for 8 bit integer numbers.
Parameters
[in] i_in 8 bit integer numbers.
Returns
value for log(x)/log(2)
Author
Stephen Gilbert
Date
2000-06-21
Definition at line 135 of file intmath.f.
References intmath::ilog2::ilog2_8().
The documentation for this module was generated from the following file:
intmath.f