var files =
[
    [ "addfield.f", "addfield_8f.html", "addfield_8f" ],
    [ "addgrid.f", "addgrid_8f.html", "addgrid_8f" ],
    [ "addlocal.f", "addlocal_8f.html", "addlocal_8f" ],
    [ "cmplxpack.f", "cmplxpack_8f.html", "cmplxpack_8f" ],
    [ "compack.f", "compack_8f.html", "compack_8f" ],
    [ "comunpack.f", "comunpack_8f.html", "comunpack_8f" ],
    [ "dec_jpeg2000.c", "dec__jpeg2000_8c.html", "dec__jpeg2000_8c" ],
    [ "dec_png.c", "dec__png_8c.html", "dec__png_8c" ],
    [ "drstemplates.f", "drstemplates_8f.html", [
      [ "drstemplate", "classdrstemplates.html#structdrstemplates_1_1drstemplate", [
        [ "mapdrs", "classdrstemplates.html#a914ea54109cb2d98dd1c5f999ed29524", null ],
        [ "mapdrslen", "classdrstemplates.html#afd40a0f291e869921c2c9b2cda8d3723", null ],
        [ "needext", "classdrstemplates.html#a1aed94ae62ca33090997a6a1b55d97d0", null ],
        [ "template_num", "classdrstemplates.html#a742a75f1b65ce691788848db25d5b196", null ]
      ] ],
      [ "drstemplates", "classdrstemplates.html", "classdrstemplates" ]
    ] ],
    [ "enc_jpeg2000.c", "enc__jpeg2000_8c.html", "enc__jpeg2000_8c" ],
    [ "enc_png.c", "enc__png_8c.html", "enc__png_8c" ],
    [ "g2_gbytesc.f", "g2__gbytesc_8f.html", "g2__gbytesc_8f" ],
    [ "g2grids.f", "g2grids_8f.html", [
      [ "g2grids", "classg2grids.html", "classg2grids" ]
    ] ],
    [ "gb_info.f", "gb__info_8f.html", "gb__info_8f" ],
    [ "gdt2gds.f", "gdt2gds_8f.html", "gdt2gds_8f" ],
    [ "getdim.f", "getdim_8f.html", "getdim_8f" ],
    [ "getfield.f", "getfield_8f.html", "getfield_8f" ],
    [ "getg2i.f", "getg2i_8f.html", "getg2i_8f" ],
    [ "getg2ir.f", "getg2ir_8f.html", "getg2ir_8f" ],
    [ "getgb2.f", "getgb2_8f.html", "getgb2_8f" ],
    [ "getgb2l.f", "getgb2l_8f_source.html", null ],
    [ "getgb2p.f", "getgb2p_8f_source.html", null ],
    [ "getgb2r.f", "getgb2r_8f_source.html", null ],
    [ "getgb2rp.f", "getgb2rp_8f_source.html", null ],
    [ "getgb2s.f", "getgb2s_8f_source.html", null ],
    [ "getidx.f", "getidx_8f_source.html", null ],
    [ "getlocal.f", "getlocal_8f_source.html", null ],
    [ "getpoly.f", "getpoly_8f_source.html", null ],
    [ "gettemplates.f", "gettemplates_8f_source.html", null ],
    [ "gf_free.f", "gf__free_8f_source.html", null ],
    [ "gf_getfld.f", "gf__getfld_8f_source.html", null ],
    [ "gf_unpack1.f", "gf__unpack1_8f_source.html", null ],
    [ "gf_unpack2.f", "gf__unpack2_8f_source.html", null ],
    [ "gf_unpack3.f", "gf__unpack3_8f_source.html", null ],
    [ "gf_unpack4.f", "gf__unpack4_8f_source.html", null ],
    [ "gf_unpack5.f", "gf__unpack5_8f_source.html", null ],
    [ "gf_unpack6.f", "gf__unpack6_8f_source.html", null ],
    [ "gf_unpack7.f", "gf__unpack7_8f_source.html", null ],
    [ "gribcreate.f", "gribcreate_8f_source.html", null ],
    [ "gribend.f", "gribend_8f_source.html", null ],
    [ "gribinfo.f", "gribinfo_8f_source.html", null ],
    [ "gribmod.f", "gribmod_8f_source.html", null ],
    [ "gridtemplates.f", "gridtemplates_8f_source.html", null ],
    [ "intmath.f", "intmath_8f_source.html", null ],
    [ "ixgb2.f", "ixgb2_8f_source.html", null ],
    [ "jpcpack.f", "jpcpack_8f_source.html", null ],
    [ "jpcunpack.f", "jpcunpack_8f_source.html", null ],
    [ "misspack.f", "misspack_8f_source.html", null ],
    [ "mkieee.f", "mkieee_8f_source.html", null ],
    [ "mova2i.c", "mova2i_8c.html", null ],
    [ "pack_gp.f", "pack__gp_8f_source.html", null ],
    [ "params.f", "params_8f_source.html", null ],
    [ "params_ecmwf.f", "params__ecmwf_8f_source.html", null ],
    [ "pdstemplates.f", "pdstemplates_8f_source.html", null ],
    [ "pngpack.f", "pngpack_8f_source.html", null ],
    [ "pngunpack.f", "pngunpack_8f_source.html", null ],
    [ "putgb2.f", "putgb2_8f_source.html", null ],
    [ "rdieee.f", "rdieee_8f_source.html", null ],
    [ "realloc.f", "realloc_8f_source.html", null ],
    [ "reduce.f", "reduce_8f_source.html", null ],
    [ "simpack.f", "simpack_8f_source.html", null ],
    [ "simunpack.f", "simunpack_8f_source.html", null ],
    [ "skgb.f", "skgb_8f_source.html", null ],
    [ "specpack.f", "specpack_8f_source.html", null ],
    [ "specunpack.f", "specunpack_8f_source.html", null ]
];