NCEPLIBS-g2: g2_gbytesc.F90 File Reference
g2_gbytesc.F90 File Reference
Extract or store arbitrary size values between packed bit string and unpacked array.
Functions/Subroutines
subroutine g2_gbytec (in, iout, iskip, nbits)
Extract arbitrary size values from a packed bit string, right justifying each value in the unpacked array without skip and interations.
subroutine g2_gbytesc (in, iout, iskip, nbits, nskip, n)
Extract arbitrary size values from a packed bit string, right justifying each value in the unpacked array with skip and interation options.
subroutine g2_sbytec (out, in, iskip, nbits)
Put arbitrary size values into a packed bit string, taking the low order bits from each value in the unpacked array without skip and interation.
subroutine g2_sbytesc (out, in, iskip, nbits, nskip, n)
Put arbitrary size values into a packed bit string, taking the low order bits from each value in the unpacked array with skip and interation options.
Detailed Description
Extract or store arbitrary size values between packed bit string and unpacked array.
Author
Stephen Gilbert
Date
2004-04-27
Definition in file g2_gbytesc.F90.
Function/Subroutine Documentation
g2_gbytec()
subroutine g2_gbytec (character*1, dimension(*), intent(in) in, integer, dimension(*), intent(inout) iout, integer, intent(in) iskip, integer, intent(in) nbits)
Extract arbitrary size values from a packed bit string, right justifying each value in the unpacked array without skip and interations.
This should be used when input array IN has only one element. If in has more elements, use g2_sbytesc().
Parameters
[in] in Array input.
[out] iout Unpacked array output.
[in] iskip Initial number of bits to skip.
[in] nbits Number of bits of each integer in IN to take.
Author
Stephen Gilbert
Date
2004-04-27
Definition at line 19 of file g2_gbytesc.F90.
References g2_gbytesc().
Referenced by addfield(), addgrid(), addlocal(), comunpack(), gb_info(), getfield(), getgb2l(), getgb2r(), getgb2rp(), getgb2s(), getlocal(), gettemplates(), gf_getfld(), gf_unpack1(), gf_unpack2(), gf_unpack3(), gf_unpack4(), gf_unpack5(), gf_unpack6(), gf_unpack7(), gribend(), gribinfo(), ixgb2(), skgb(), unpack3(), unpack4(), unpack5(), and unpack6().
g2_gbytesc()
subroutine g2_gbytesc (character*1, dimension(*), intent(in) in, integer, dimension(*), intent(out) iout, integer, intent(in) iskip, integer, intent(in) nbits, integer, intent(in) nskip, integer, intent(in) n)
Extract arbitrary size values from a packed bit string, right justifying each value in the unpacked array with skip and interation options.
Parameters
[in] in array input
[out] iout unpacked array output
[in] iskip initial number of bits to skip
[in] nbits Number of bits of each integer in IN to take.
[in] nskip Additional number of bits to skip on each iteration.
[in] n Number of integers to extract.
Author
Stephen Gilbert
Date
2004-04-27
Definition at line 62 of file g2_gbytesc.F90.
Referenced by comunpack(), g2_gbytec(), gf_unpack3(), gf_unpack4(), gf_unpack6(), pngunpack(), simunpack(), specunpack(), unpack3(), unpack4(), and unpack6().
g2_sbytec()
subroutine g2_sbytec (character*1, dimension(*), intent(inout) out, integer, dimension(*), intent(in) in, integer, intent(in) iskip, integer, intent(in) nbits)
Put arbitrary size values into a packed bit string, taking the low order bits from each value in the unpacked array without skip and interation.
This should be used when input array IN has only one element. If IN has more elements, use G2_SBYTESC().
Parameters
[out] out packed array output
[in] in unpacked array input
[in] iskip initial number of bits to skip
[in] nbits Number of bits of each integer in OUT to fill.
Author
Stephen Gilbert
Date
2004-04-27
Definition at line 41 of file g2_gbytesc.F90.
References g2_sbytesc().
Referenced by addfield(), addgrid(), addlocal(), compack(), getgb2rp(), gribcreate(), gribend(), ixgb2(), misspack(), and simpack().
g2_sbytesc()
subroutine g2_sbytesc (character*1, dimension(*), intent(out) out, integer, dimension(n), intent(in) in, integer, intent(in) iskip, integer, intent(in) nbits, integer, intent(in) nskip, integer, intent(in) n)
Put arbitrary size values into a packed bit string, taking the low order bits from each value in the unpacked array with skip and interation options.
Parameters
[out] out Packed array output.
[in] in Unpacked array input.
[in] iskip Initial number of bits to skip.
[in] nbits Number of bits of each integer in OUT to fill.
[in] nskip Additional number of bits to skip on each iteration.
[in] n Number of iterations.
Author
Stephen Gilbert
Date
2004-04-27
Definition at line 119 of file g2_gbytesc.F90.
Referenced by addfield(), addgrid(), compack(), g2_sbytec(), jpcpack(), misspack(), pngpack(), and simpack().