NCEPLIBS-g2: g2_gbytesc.f File Reference
g2_gbytesc.f File Reference
This Fortran module extract or store arbitrary size values between packed bit string and unpacked array.
Functions/Subroutines
subroutine g2_gbytec (IN, IOUT, ISKIP, NBYTE)
This subrountine is to extract arbitrary size values from a packed bit string, right justifying each value in the unpacked array without skip and interations.
subroutine g2_gbytesc (IN, IOUT, ISKIP, NBYTE, NSKIP, N)
This subrountine is to extract arbitrary size values from a packed bit string, right justifying each value in the unpacked array with skip and interation options.
subroutine g2_sbytec (OUT, IN, ISKIP, NBYTE)
This subrountine is to put arbitrary size values into a packed bit string, taking the low order bits from each value in the unpacked array without skip and interation.
subroutine g2_sbytesc (OUT, IN, ISKIP, NBYTE, NSKIP, N)
This subrountine is to put arbitrary size values into a packed bit string, taking the low order bits from each value in the unpacked array with skip and interation options.
Detailed Description
This Fortran module extract or store arbitrary size values between packed bit string and unpacked array.
Author
Stephen Gilbert
Date
2004-04-27
Definition in file g2_gbytesc.f.
Function/Subroutine Documentation
subroutine g2_gbytec (character*1, dimension(*) IN, integer, dimension(*) IOUT, ISKIP, NBYTE)
This subrountine is to extract arbitrary size values from a packed bit string, right justifying each value in the unpacked array without skip and interations.
Parameters
[in] IN character*1 array input
[out] IOUT unpacked array output
[in] ISKIP initial number of bits to skip
[in] NBYTE number of bits to take
Author
Stephen Gilbert
Date
2004-04-27
Definition at line 19 of file g2_gbytesc.f.
References g2_gbytesc().
Referenced by addfield(), addgrid(), addlocal(), comunpack(), gb_info(), getfield(), getgb2l(), getgb2r(), getgb2rp(), getgb2s(), getlocal(), gettemplates(), gf_getfld(), gf_unpack1(), gf_unpack2(), gf_unpack3(), gf_unpack4(), gf_unpack5(), gf_unpack6(), gf_unpack7(), gribend(), gribinfo(), ixgb2(), skgb(), unpack3(), unpack4(), unpack5(), and unpack6().
subroutine g2_gbytesc (character*1, dimension(*) IN, integer, dimension(*) IOUT, ISKIP, NBYTE, NSKIP, N)
This subrountine is to extract arbitrary size values from a packed bit string, right justifying each value in the unpacked array with skip and interation options.
Parameters
[in] IN character*1 array input
[out] IOUT unpacked array output
[in] ISKIP initial number of bits to skip
[in] NBYTE number of bits to take
[in] NSKIP additional number of bits to skip on each iteration
[in] N number of iterations
Author
Stephen Gilbert
Date
2004-04-27
Definition at line 59 of file g2_gbytesc.f.
Referenced by comunpack(), g2_gbytec(), gf_unpack3(), gf_unpack4(), gf_unpack6(), pngunpack(), simunpack(), specunpack(), unpack3(), unpack4(), and unpack6().
subroutine g2_sbytec (character*1, dimension(*) OUT, integer, dimension(*) IN, ISKIP, NBYTE)
This subrountine is to put arbitrary size values into a packed bit string, taking the low order bits from each value in the unpacked array without skip and interation.
Parameters
[out] OUT packed array output
[in] IN unpacked array input
[in] ISKIP initial number of bits to skip
[in] NBYTE number of bits to pack
Author
Stephen Gilbert
Date
2004-04-27
Definition at line 38 of file g2_gbytesc.f.
References g2_sbytesc().
Referenced by addfield(), addgrid(), addlocal(), compack(), getgb2rp(), gribcreate(), gribend(), ixgb2(), misspack(), and simpack().
subroutine g2_sbytesc (character*1, dimension(*) OUT, integer, dimension(n) IN, ISKIP, NBYTE, NSKIP, N)
This subrountine is to put arbitrary size values into a packed bit string, taking the low order bits from each value in the unpacked array with skip and interation options.
Parameters
[out] OUT packed array output
[in] IN unpacked array input
[in] ISKIP initial number of bits to skip
[in] NBYTE number of bits to pack
[in] NSKIP additional number of bits to skip on each iteration
[in] N number of iterations
Author
Stephen Gilbert
Date
2004-04-27
Definition at line 114 of file g2_gbytesc.f.
Referenced by addfield(), addgrid(), compack(), g2_sbytec(), jpcpack(), misspack(), pngpack(), and simpack().