NCEPLIBS-g2: getg2ir.F90 File Reference
getg2ir.F90 File Reference
This subroutine reads a GRIB file and returns its index content.
Functions/Subroutines
subroutine getg2ir (lugb, msk1, msk2, mnum, cbuf, nlen, nnum, nmess, iret)
This subroutine reads a GRIB file and returns its index content.
Detailed Description
This subroutine reads a GRIB file and returns its index content.
Author
Mark Iredell
Date
1995-10-31
Definition in file getg2ir.F90.
Function/Subroutine Documentation
getg2ir()
subroutine getg2ir (integer, intent(in) lugb, integer, intent(in) msk1, integer, intent(in) msk2, integer, intent(in) mnum, character(len = 1), dimension(:), pointer cbuf, integer, intent(out) nlen, integer, intent(out) nnum, integer, intent(out) nmess, integer, intent(out) iret)
This subroutine reads a GRIB file and returns its index content.
The index buffer returned contains index records with the internal format:
byte 001 - 004 length of index record
byte 005 - 008 bytes to skip in data file before grib message
byte 009 - 012 bytes to skip in message before lus (local use) set = 0, if no local use section in grib2 message.
byte 013 - 016 bytes to skip in message before gds
byte 017 - 020 bytes to skip in message before pds
byte 021 - 024 bytes to skip in message before drs
byte 025 - 028 bytes to skip in message before bms
byte 029 - 032 bytes to skip in message before data section
byte 033 - 040 bytes total in the message
byte 041 - 041 grib version number (currently 2)
byte 042 - 042 message discipline
byte 043 - 044 field number within grib2 message
byte 045 - ii identification section (ids)
byte ii+1- jj grid definition section (gds)
byte jj+1- kk product definition section (pds)
byte kk+1- ll the data representation section (drs)
byte ll+1-ll+6 first 6 bytes of the bit map section (bms)
Program History Log
Date Programmer Comments
1995-10-31 Mark Iredell Initial
1996-10-31 Mark Iredell augmented optional definitions to byte 320
2002-01-02 Stephen Gilbert modified from getgir to create grib2 indexes
Parameters
[in] lugb Unit of the unblocked grib file. Must be opened by baopen() or baopenr().
[in] msk1 Number of bytes to search for first message.
[in] msk2 Number of bytes to search for other messages.
[in] mnum Number of grib messages to skip (usually 0).
[out] cbuf Pointer to a buffer that will get the index records. If any memory is associated with cbuf when this subroutine is called, cbuf will be nullified in the subroutine. Initially cbuf will get an allocation of 5000 bytes. realloc() will be used to increase the size if necessary. Users must free memory that cbuf points to when cbuf is no longer needed.
[out] nlen Total length of index record buffer in bytes.
[out] nnum Number of index records, =0 if no grib messages are found).
[out] nmess Last grib message in file successfully processed
[out] iret Return code.
0 all ok
1 not enough memory available to hold full index buffer
2 not enough memory to allocate initial index buffer
Note
Subprogram can be called from a multiprocessing environment. Do not engage the same logical unit from more than one processor.
Author
Mark Iredell
Date
1995-10-31
Definition at line 62 of file getg2ir.F90.
References ixgb2(), and skgb().
Referenced by getgb2p(), and getidx().