NCEPLIBS-g2: getgb2r.F90 File Reference
getgb2r.F90 File Reference
This subroutine reads and unpacks sections 6 and 7 from a GRIB2 message.
Functions/Subroutines
subroutine getgb2r (LUGB, CINDEX, GFLD, IRET)
This subroutine reads and unpacks sections 6 and 7 from a GRIB2 message.
Detailed Description
This subroutine reads and unpacks sections 6 and 7 from a GRIB2 message.
Author
Stephen Gilbert
Date
2002-01-11
Definition in file getgb2r.F90.
Function/Subroutine Documentation
getgb2r()
subroutine getgb2r (integer, intent(in) LUGB, character(len = 1), dimension(*), intent(in) CINDEX, type(gribfield) GFLD, integer, intent(out) IRET)
This subroutine reads and unpacks sections 6 and 7 from a GRIB2 message.
It assumes that the metadata for this field already exists in derived type grib_mod::gribfield. Specifically, it requires gfld%ibmap, gfld%ngrdpts, gfld%idrtnum, gfld%idrtmpl, and gfld%ndpts.
It decodes information for the selected grib field and returns it in a derived type variable, gfld, of type grib_mod::gribfield. Users of this routine will need to include the line "use grib_mod" in their calling routine.
Parameters
[in] LUGB integer unit of the unblocked grib data file. File must be opened with baopen() or baopenr() before calling this routine.
[in] CINDEX index record of the grib field (see subroutine ixgb2() for description of an index record.)
[out] GFLD derived type grib_mod::gribfield.
[out] IRET integer return code
0 all ok
97 error reading grib file
other gf_getfld grib2 unpacker return code
Note
Do not engage the same logical unit from more than one processor. This subprogram is intended for private use by getgb2 routines only. Note that derived type gribfield contains pointers to many arrays of data. The memory for these arrays is allocated when the values in the arrays are set, to help minimize problems with array overloading. Users should free this memory, when it is no longer needed, by a call to subroutine gf_free().
Author
Stephen Gilbert
Date
2002-01-11
Definition at line 41 of file getgb2r.F90.
References g2_gbytec(), gf_unpack6(), and gf_unpack7().
Referenced by getgb2().