NCEPLIBS-g2: gf_unpack7.F90 File Reference
gf_unpack7.F90 File Reference
Unpack Section 7 (Data Section) of a GRIB2 message.
Functions/Subroutines
subroutine gf_unpack7 (cgrib, lcgrib, iofst, igdsnum, igdstmpl, idrsnum, idrstmpl, ndpts, fld, ierr)
Unpack Section 7 (Data Section) of a GRIB2 message.
Detailed Description
Unpack Section 7 (Data Section) of a GRIB2 message.
Author
Stephen Gilbert
Date
2002-01-24
Definition in file gf_unpack7.F90.
Function/Subroutine Documentation
gf_unpack7()
subroutine gf_unpack7 (character(len = 1), dimension(lcgrib), intent(in) cgrib, integer, intent(in) lcgrib, integer, intent(inout) iofst, integer, intent(in) igdsnum, integer, dimension(:), pointer igdstmpl, integer, intent(in) idrsnum, integer, dimension(:), pointer idrstmpl, integer, intent(in) ndpts, real, dimension(:), pointer fld, integer, intent(out) ierr)
Unpack Section 7 (Data Section) of a GRIB2 message.
Parameters
[in] cgrib Character array that contains the GRIB2 message.
[in] lcgrib Length (in bytes) of GRIB message array cgrib.
[in,out] iofst Bit offset of the beginning/end(returned) of Section 7.
[in] igdsnum Grid Definition Template Number (Code Table 3.0) (Only required to unpack DRT 5.51).
[in] igdstmpl Pointer to an integer array containing the data values for the specified Grid Definition. Template (N = igdsnum). Each element of this integer array contains an entry (in the order specified) of Grid Definition Template 3.N (Only required to unpack DRT 5.51).
[in] idrsnum Data Representation Template Number (Code Table 5.0).
[in] idrstmpl Pointer to an integer array containing the data values for the Data Representation Template specified by idrsnum. A safe dimension for this array can be obtained in advance from maxvals(6), which is returned from subroutine gribinfo.
[in] ndpts Number of data points unpacked and returned.
[out] fld Pointer to a real array containing the unpacked data field.
[out] ierr Error return code.
0 no error.
4 Unrecognized Data Representation Template.
5 One of GDT 3.50 through 3.53 required to unpack DRT 5.51.
6 memory allocation error.
7 corrupt section 7.
Author
Stephen Gilbert
Date
2002-01-24
Definition at line 40 of file gf_unpack7.F90.
References comunpack(), g2_gbytec(), jpcunpack(), pngunpack(), rdieee(), simunpack(), and specunpack().
Referenced by getgb2r(), and gf_getfld().