NCEPLIBS-g2: gf_unpack5.F90 File Reference
gf_unpack5.F90 File Reference
Contains subroutines unpacks Section 5 (Data Representation Section) of a GRIB2 message.
Functions/Subroutines
subroutine gf_unpack5 (cgrib, lcgrib, iofst, ndpts, idrsnum, idrstmpl, mapdrslen, ierr)
This subroutine unpacks Section 5 (Data Representation Section) of a GRIB2 message, starting at octet 6 of that Section.
Detailed Description
Contains subroutines unpacks Section 5 (Data Representation Section) of a GRIB2 message.
Author
Stephen Gilbert
Date
2000-05-26
Definition in file gf_unpack5.F90.
Function/Subroutine Documentation
gf_unpack5()
subroutine gf_unpack5 (character(len = 1), dimension(lcgrib), intent(in) cgrib, integer, intent(in) lcgrib, integer, intent(inout) iofst, integer, intent(out) ndpts, integer, intent(out) idrsnum, integer, dimension(:), pointer idrstmpl, integer mapdrslen, integer, intent(out) ierr)
This subroutine unpacks Section 5 (Data Representation Section) of a GRIB2 message, starting at octet 6 of that Section.
Program History Log
Date Programmer Comments
2000-05-26 Stephen Gilbert Initial development.
2002-01-24 Stephen Gilbert Allocate arrays and to pass pointers.
Parameters
[in] cgrib Character array that contains the GRIB2 message.
[in] lcgrib Length (in bytes) of GRIB message array cgrib.
[in,out] iofst Bit offset of the beginning/end(returned) of Section 5.
[out] ndpts Number of data points unpacked and returned.
[out] idrsnum Data Representation Template Number (Code Table 5.0).
[out] idrstmpl Contains the data values for the specified Data Representation Template (N=idrsnum). Each element of this integer array contains an entry (in the order specified) of Product Defintion Template 5.N A safe dimension for this array can be obtained in advance from maxvals(6), which is returned from subroutine gribinfo.
[out] mapdrslen Number of elements in idrstmpl. i.e. number of entries in Data Representation Template 5.N (N=idrsnum).
[out] ierr Error return code.
0 no error.
6 memory allocation error.
7 "GRIB" message contains an undefined Grid Definition Template.
Author
Stephen Gilbert
Date
2000-05-26
Definition at line 41 of file gf_unpack5.F90.
References drstemplates::extdrstemplate(), g2_gbytec(), and drstemplates::getdrstemplate().
Referenced by getgb2s(), and gf_getfld().