NCEPLIBS-g2: intmath::ilog2 Interface Reference
intmath::ilog2 Interface Reference
Public Member Functions
integer(kind=1) function ilog2_1 (i_in)
This function returns log(x)/log(2) for 1 bit integer numbers.
integer(kind=2) function ilog2_2 (i_in)
This function returns log(x)/log(2) for 2 bit integer numbers.
integer(kind=4) function ilog2_4 (i_in)
This function returns log(x)/log(2) for 4 bit integer numbers.
integer(kind=8) function ilog2_8 (i_in)
This function returns log(x)/log(2) for 8 bit integer numbers.
Detailed Description
Definition at line 25 of file intmath.f.
Member Function/Subroutine Documentation
integer(kind=1) function intmath::ilog2::ilog2_1 (integer(kind=1) i_in)
This function returns log(x)/log(2) for 1 bit integer numbers.
Parameters
[in] i_in 1 bit integer numbers.
Returns
value for log(x)/log(2)
Author
Stephen Gilbert
Date
2000-06-21
Definition at line 273 of file intmath.f.
Referenced by intmath::i1log2_1(), and intmath::ilog2_1().
integer(kind=2) function intmath::ilog2::ilog2_2 (integer(kind=2) i_in)
This function returns log(x)/log(2) for 2 bit integer numbers.
Parameters
[in] i_in 2 bit integer numbers.
Returns
value for log(x)/log(2)
Author
Stephen Gilbert
Date
2000-06-21
Definition at line 232 of file intmath.f.
Referenced by intmath::i1log2_2(), and intmath::ilog2_2().
integer(kind=4) function intmath::ilog2::ilog2_4 (integer(kind=4) i_in)
This function returns log(x)/log(2) for 4 bit integer numbers.
Parameters
[in] i_in 4 bit integer numbers.
Returns
value for log(x)/log(2)
Author
Stephen Gilbert
Date
2000-06-21
Definition at line 186 of file intmath.f.
Referenced by intmath::i1log2_4(), and intmath::ilog2_4().
integer(kind=8) function intmath::ilog2::ilog2_8 (integer(kind=8) i_in)
This function returns log(x)/log(2) for 8 bit integer numbers.
Parameters
[in] i_in 8 bit integer numbers.
Returns
value for log(x)/log(2)
Author
Stephen Gilbert
Date
2000-06-21
Definition at line 135 of file intmath.f.
Referenced by intmath::i1log2_8(), and intmath::ilog2_8().
The documentation for this interface was generated from the following file:
intmath.f