NCEPLIBS-g2: intmath::i1log2 Interface Reference
intmath::i1log2 Interface Reference
Public Member Functions
integer(kind=1) function i1log2_1 (ival)
This function returns log(x+1)/log(2) unless x=maxint, in which case log(x)/log(2) for 1 bit integer numbers.
integer(kind=2) function i1log2_2 (ival)
This function returns log(x+1)/log(2) unless x=maxint, in which case log(x)/log(2) for 2 bit integer numbers.
integer(kind=4) function i1log2_4 (ival)
This function returns log(x+1)/log(2) unless x=maxint, in which case log(x)/log(2) for 4 bit integer numbers.
integer(kind=8) function i1log2_8 (ival)
This function returns log(x+1)/log(2) unless x=maxint, in which case log(x)/log(2) for 8 bit integer numbers.
Detailed Description
Definition at line 33 of file intmath.F90.
Member Function/Subroutine Documentation
i1log2_1()
integer(kind=1) function intmath::i1log2::i1log2_1 (integer(kind=1), value ival)
This function returns log(x+1)/log(2) unless x=maxint, in which case log(x)/log(2) for 1 bit integer numbers.
Parameters
[in] ival 1 bit integer numbers.
Returns
value for log(x+1)/log(2)
Author
Stephen Gilbert
Date
2000-06-21
Definition at line 99 of file intmath.F90.
References intmath::i1log2_1(), and intmath::ilog2_1().
i1log2_2()
integer(kind=2) function intmath::i1log2::i1log2_2 (integer(kind=2), value ival)
This function returns log(x+1)/log(2) unless x=maxint, in which case log(x)/log(2) for 2 bit integer numbers.
Parameters
[in] ival 2 bit integer numbers.
Returns
value for log(x+1)/log(2)
Author
Stephen Gilbert
Date
2000-06-21
Definition at line 82 of file intmath.F90.
References intmath::i1log2_2(), and intmath::ilog2_2().
i1log2_4()
integer(kind=4) function intmath::i1log2::i1log2_4 (integer(kind=4), value ival)
This function returns log(x+1)/log(2) unless x=maxint, in which case log(x)/log(2) for 4 bit integer numbers.
Parameters
[in] ival 4 bit integer numbers.
Returns
value for log(x+1)/log(2)
Author
Stephen Gilbert
Date
2000-06-21
Definition at line 65 of file intmath.F90.
References intmath::i1log2_4(), and intmath::ilog2_4().
i1log2_8()
integer(kind=8) function intmath::i1log2::i1log2_8 (integer(kind=8), value ival)
This function returns log(x+1)/log(2) unless x=maxint, in which case log(x)/log(2) for 8 bit integer numbers.
Parameters
[in] ival 8 bit integer numbers.
Returns
value for log(x+1)/log(2)
Author
Stephen Gilbert
Date
2000-06-21
Definition at line 48 of file intmath.F90.
References intmath::i1log2_8(), and intmath::ilog2_8().
The documentation for this interface was generated from the following file:
intmath.F90