NCEPLIBS-g2: params Module Reference
params Module Reference
This Fortran Module contains info on all the available GRIB Parameters, and their GRIB1 and GRIB2 codes.
Data Types
type gribparam
This type holds information about GRIB parameters.
Functions/Subroutines
subroutine param_g1_to_g2 (g1val, g1ver, g2disc, g2cat, g2num)
This subroutine returns the corresponding GRIB2 Discipline Category and Number for a given GRIB1 parameter value and table version.
subroutine param_g2_to_g1 (g2disc, g2cat, g2num, g1val, g1ver)
This subroutine returns the GRIB 1 parameter number for a given GRIB2 Discipline, Category and Parameter number.
character(len=8) function param_get_abbrev (g2disc, g2cat, g2num)
This function returns the parameter abbreviation for a given GRIB2 Discipline, Category and Parameter number.
Variables
integer, parameter maxparam = 2000
maximum number of GRIB parameters.
type(gribparam), dimension(maxparam) paramlist
list of GRIB parameters.
Detailed Description
This Fortran Module contains info on all the available GRIB Parameters, and their GRIB1 and GRIB2 codes.
If both of the GRIB1 codes are 255, that means the parameters is "UNKNOWN" in GRIB1 and cannot be converted to GRIB1.
Author
Stephen Gilbert
Date
2001-06-05
Author
Brent Gordon, Boi Vuong
Data Type Documentation
params::gribparam
type params::gribparam
This type holds information about GRIB parameters.
Definition at line 17 of file params.F90.
Data Fields
character(len=8) abbrev Abbreviation.
integer g1tblver GRIB1 table version.
integer grib1val GRIB1 value.
integer grib2cat GRIB2 category number.
integer grib2dsc GRIB2 discipline category.
integer grib2num GRIB2 parameter number.
Function/Subroutine Documentation
param_g1_to_g2()
subroutine params::param_g1_to_g2 (integer, intent(in) g1val, integer, intent(in) g1ver, integer, intent(out) g2disc, integer, intent(out) g2cat, integer, intent(out) g2num)
This subroutine returns the corresponding GRIB2 Discipline Category and Number for a given GRIB1 parameter value and table version.
Parameters
[in] g1val GRIB1 parameter number for which discipline is requested.
[in] g1ver GRIB1 parameter table version number.
[out] g2disc corresponding GRIB2 Discipline number.
[out] g2cat corresponding GRIB2 Category number.
[out] g2num corresponding GRIB2 Parameter number within Category g2cat.
Author
Stephen Gilbert
Date
2001-06-05
Definition at line 1076 of file params.F90.
References maxparam, and paramlist.
param_g2_to_g1()
subroutine params::param_g2_to_g1 (integer, intent(in) g2disc, integer, intent(in) g2cat, integer, intent(in) g2num, integer, intent(out) g1val, integer, intent(out) g1ver)
This subroutine returns the GRIB 1 parameter number for a given GRIB2 Discipline, Category and Parameter number.
Parameters
[in] g2disc GRIB2 Discipline number (See Code Table 0.0).
[in] g2cat corresponding GRIB2 Category number.
[in] g2num corresponding GRIB2 Parameter number within Category g2cat.
[out] g1val GRIB1 parameter number for which discipline is requested.
[out] g1ver GRIB1 parameter table version number.
Author
Stephen Gilbert
Date
2002-01-04
Definition at line 1146 of file params.F90.
References maxparam, and paramlist.
param_get_abbrev()
character(len = 8) function params::param_get_abbrev (integer, intent(in) g2disc, integer, intent(in) g2cat, integer, intent(in) g2num)
This function returns the parameter abbreviation for a given GRIB2 Discipline, Category and Parameter number.
Parameters
[in] g2disc GRIB2 discipline number (See Code Table 0.0).
[in] g2cat corresponding GRIB2 Category number.
[in] g2num corresponding GRIB2 Parameter number within Category g2cat.
Returns
parameter abbreviation for GRIB2 info.
Author
Stephen Gilbert
Date
2002-01-04
Definition at line 1112 of file params.F90.
References maxparam, and paramlist.
Variable Documentation
maxparam
integer, parameter params::maxparam = 2000
maximum number of GRIB parameters.
Definition at line 14 of file params.F90.
Referenced by param_g1_to_g2(), param_g2_to_g1(), and param_get_abbrev().
paramlist
type(gribparam), dimension(maxparam) params::paramlist
list of GRIB parameters.
Definition at line 26 of file params.F90.
Referenced by param_g1_to_g2(), param_g2_to_g1(), and param_get_abbrev().