NCEPLIBS-g2: gridtemplates Module Reference
gridtemplates Module Reference
This Fortran module contains info on all the available GRIB2 Grid Definition Templates used in [Section 3 - the Grid Definition Section (GDS)](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_sect3.shtml).
Data Types
type gridtemplate
Functions/Subroutines
subroutine extgridtemplate (number, list, nummap, map)
Generate the remaining byte map for a given Grid Definition Template, if required.
integer function getgdtlen (number)
Return the initial length (number of entries) in the static part of specified Grid Definition Template.
integer function getgridindex (number)
This function returns the index of the specified Grid Definition Template in the templates array.
subroutine getgridtemplate (number, nummap, map, needext, iret)
Get the template information for a specified Grid Definition Template.
Variables
integer, parameter maxlen =200
maximum number of octets in mapgrid
integer, parameter maxtemp =31
maximum number of entries in the template
type(gridtemplate), dimension(maxtemp) templates
a gridtemplate type
Detailed Description
This Fortran module contains info on all the available GRIB2 Grid Definition Templates used in [Section 3 - the Grid Definition Section (GDS)](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_sect3.shtml).
Each Template has three parts:
The number of entries in the template (mapgridlen);
A map of the template (mapgrid), which contains the number of octets in which to pack each of the template values;
A logical value (needext) that indicates whether the Template needs to be extended. In some cases the number of entries in a template can vary depending upon values specified in the "static" part of the template. (See Template 3.120 as an example).
This module also contains two subroutines. Subroutine getgridtemplate() returns the octet map for a specified Template number, and subroutine extgridtemplate() will calculate the extended octet map of an appropriate template given values for the static part of the template.
Note
Array mapgrid contains the number of bytes in which the corresponding template values will be stored. A negative value in mapgrid is used to indicate that the corresponding template entry can contain negative values. This information is used later when packing/unpacking the template data values. Negative data values in GRIB are stored with the left most bit set to one, and a negative number of bytes value in mapgrid indicates that this possibility should be considered. The number of bytes used to store the data value in this case would be the absolute value of the negative value in mapgrid.
Program History Log
Date Programmer Comments
2000-05-09 Stephen Gilbert Initial development
2003-09-02 Stephen Gilbert Added GDT 3.31 Albers Equal Area
2007-04-24 Boi Vuong Added GDT 3.204 Curilinear Orthogonal Grids
2008-05-29 Boi Vuong Added GDT 3.32768 Rotate Lat/Lon E-grid
2010-05-10 Boi Vuong Added GDT 3.32769 Rotate Lat/Lon Non E-Stagger grid
2013-08-06 Boi Vuong Added GDT 3.4,3.5,3.12,3.101,3.140
Author
Stephen Gilbert
Date
2000-05-09
Data Type Documentation
gridtemplates::gridtemplate
type gridtemplates::gridtemplate
Definition at line 54 of file gridtemplates.F90.
Data Fields
integer, dimension(maxlen) mapgrid The number of octets in which to pack each of the template values.
integer mapgridlen Number of entries in the template.
logical needext Does template need to be extended?
integer template_num Grid Definition Template Number.
Function/Subroutine Documentation
extgridtemplate()
subroutine gridtemplates::extgridtemplate (integer, intent(in) number, integer, dimension(*), intent(in) list, integer, intent(out) nummap, integer, dimension(*), intent(out) map)
Generate the remaining byte map for a given Grid Definition Template, if required.
Some Templates can vary depending on data values given in an earlier part of the Template, and it is necessary to know some of the earlier entry values to generate the full octet map of the Template.
Parameters
[in] number the Grid Definition Template being requested.
[in] list The list of values for each entry in the Grid Definition Template.
[out] nummap Number of entries in the Template.
[out] map An array containing the number of bytes that each template entry occupies when packed up into the GDS.
Author
Stephen Gilbert
Date
2000-05-09
Definition at line 342 of file gridtemplates.F90.
References getgridindex(), and templates.
Referenced by addgrid(), gf_unpack3(), and unpack3().
getgdtlen()
integer function gridtemplates::getgdtlen (integer, intent(in) number)
Return the initial length (number of entries) in the static part of specified Grid Definition Template.
Parameters
[in] number the Grid Definition Template being requested.
Returns
Number of entries in the static part of GDT. Or 0, if requested template is not found.
Author
Stephen Gilbert
Date
2004-05-11
Definition at line 408 of file gridtemplates.F90.
References getgridindex(), and templates.
getgridindex()
integer function gridtemplates::getgridindex (integer, intent(in) number)
This function returns the index of the specified Grid Definition Template in the templates array.
Parameters
[in] number the number of the Grid Definition Template that is being requested.
Returns
Index of the Grid Definition Template in the templates array, if it exists. -1, otherwise.
Author
Stephen Gilbert
Date
2001-06-28
Definition at line 267 of file gridtemplates.F90.
References maxtemp, and templates.
Referenced by extgridtemplate(), getgdtlen(), and getgridtemplate().
getgridtemplate()
subroutine gridtemplates::getgridtemplate (integer, intent(in) number, integer, intent(out) nummap, integer, dimension(*), intent(out) map, logical, intent(out) needext, integer, intent(out) iret)
Get the template information for a specified Grid Definition Template.
The number of entries in the template is returned along with a map of the number of bytes occupied by each entry. Also, a flag is returned to indicate whether the template would need to be extended.
Parameters
[in] number the Grid Definition Template being requested.
[out] nummap Number of entries in the Template.
[out] map An array containing the number of bytes that each template entry occupies when packed up into the GDS.
[out] needext Logical variable indicating whether the Grid Defintion Template has to be extended.
[out] iret Error return code.
0 no error.
1 Undefine Grid Template number.
Author
Stephen Gilbert
Date
2000-05-09
Definition at line 302 of file gridtemplates.F90.
References getgridindex(), and templates.
Referenced by addgrid(), gf_unpack3(), and unpack3().
Variable Documentation
maxlen
integer, parameter gridtemplates::maxlen =200
maximum number of octets in mapgrid
Definition at line 51 of file gridtemplates.F90.
maxtemp
integer, parameter gridtemplates::maxtemp =31
maximum number of entries in the template
Definition at line 52 of file gridtemplates.F90.
Referenced by getgridindex().
templates
type(gridtemplate), dimension(maxtemp) gridtemplates::templates
a gridtemplate type
Definition at line 63 of file gridtemplates.F90.
Referenced by extgridtemplate(), getgdtlen(), getgridindex(), and getgridtemplate().