NCEPLIBS-g2: rdieee.f File Reference
rdieee.f File Reference
This subroutine reads 32-bit IEEE floating point values.
Functions/Subroutines
subroutine rdieee (rieee, a, num)
This subroutine reads a list of real values in 32-bit IEEE floating point format.
Detailed Description
This subroutine reads 32-bit IEEE floating point values.
Author
Stephen Gilbert
Date
2000-05-09
Definition in file rdieee.f.
Function/Subroutine Documentation
rdieee()
subroutine rdieee (real(4), dimension(num), intent(in) rieee, real, dimension(num), intent(out) a, integer, intent(in) num)
This subroutine reads a list of real values in 32-bit IEEE floating point format.
Parameters
[in] rieee Input array of floating point values in 32-bit IEEE format.
[in] num Number of floating point values to convert.
[out] a Output array of real values.
Author
Stephen Gilbert
Date
2000-05-09
Definition at line 15 of file rdieee.f.
Referenced by comunpack(), getfield(), gf_unpack4(), gf_unpack7(), jpcunpack(), misspack(), pngunpack(), simunpack(), specunpack(), and unpack4().