! This is a test program for NCEPLIBS-g2.
!
! This program tests index file functionality with getg2ir() and
! getg2i() with the test GDAS file.
!
! Ed Hartnett 5/17/23
program test_getg2ir_gdas
  use bacio_module
  use index_rec
  implicit none

  ! These are the test files we will use.
  character(*) :: TEST_FILE_GDAS
  parameter (TEST_FILE_GDAS = 'gdaswave.t00z.wcoast.0p16.f000.grib2')
  character(*) :: TEST_FILE_GDAS_INDEX
  parameter (TEST_FILE_GDAS_INDEX = 'ref_gdaswave.t00z.wcoast.0p16.f000.grb2index')

  integer :: LUGB, LUGI
  parameter(LUGB = 3, LUGI = 4)
  integer :: NUM_MESSAGES
  parameter(NUM_MESSAGES = 19)
  integer :: INDEX_REC_LEN
  parameter(INDEX_REC_LEN = 200)
  character(len=1), pointer, dimension(:) :: cbuf(:)
  integer :: BYTES_TO_SEARCH
  parameter(BYTES_TO_SEARCH = 1000)
  integer :: mnum
  integer :: nlen, nnum, nmess, iret
  integer :: nlen_expected
  type (index_rec_data) :: idx, expected_idx(NUM_MESSAGES)

  interface
     subroutine getg2ir(lugb, msk1, msk2, mnum, cbuf, nlen, nnum, nmess, iret)
       integer, intent(in) :: lugb, msk1, msk2, mnum
       character(len = 1),pointer,dimension(:) :: cbuf
       integer, intent(out) :: nlen, nnum, nmess, iret
     end subroutine getg2ir
  end interface

  interface
     subroutine getg2i(lugi,cbuf,nlen,nnum,iret)
       integer,intent(in) :: lugi
       character(len=1),pointer,dimension(:) :: cbuf
       integer,intent(out) :: nlen, nnum, iret
     end subroutine getg2i
  end interface

  print *, 'Testing index functions on GDAS test file and index.'

  ! Initialize expected results. These numbers can also be seen in a
  ! degrib2 of the file.
  call init_index(INDEX_REC_LEN, 0, 0, 37, 109, 143, 166, 4721, 15254, 2, 0, 1, expected_idx(1))
  call init_index(INDEX_REC_LEN, 15254, 0, 37, 109, 143, 166, 4721, 22643, 2, 0, 1, expected_idx(2))
  call init_index(INDEX_REC_LEN, 37897, 0, 37, 109, 143, 166, 4721, 15897, 2, 0, 1, expected_idx(3))
  call init_index(INDEX_REC_LEN, 53794, 0, 37, 109, 143, 166, 4721, 15270, 2, 0, 1, expected_idx(4))
  call init_index(INDEX_REC_LEN, 69064, 0, 37, 109, 143, 166, 4721, 10418, 2, 10, 1, expected_idx(5))
  call init_index(INDEX_REC_LEN, 79482, 0, 37, 109, 143, 166, 4721, 11826, 2, 10, 1, expected_idx(6))
  call init_index(INDEX_REC_LEN, 91308, 0, 37, 109, 143, 166, 4721, 17233, 2, 10, 1, expected_idx(7))
  call init_index(INDEX_REC_LEN, 108541, 0, 37, 109, 143, 166, 4721, 8175, 2, 10, 1, expected_idx(8))
  call init_index(INDEX_REC_LEN, 116716, 0, 37, 109, 143, 166, 4721, 12116, 2, 10, 1, expected_idx(9))
  call init_index(INDEX_REC_LEN, 128832, 0, 37, 109, 143, 166, 4721, 12016, 2, 10, 1, expected_idx(10))
  call init_index(INDEX_REC_LEN, 140848, 0, 37, 109, 143, 166, 4721, 10884, 2, 10, 1, expected_idx(11))
  call init_index(INDEX_REC_LEN, 151732, 0, 37, 109, 143, 166, 4721, 9289, 2, 10, 1, expected_idx(12))
  call init_index(INDEX_REC_LEN, 161021, 0, 37, 109, 143, 166, 4721, 12655, 2, 10, 1, expected_idx(13))
  call init_index(INDEX_REC_LEN, 173676, 0, 37, 109, 143, 166, 4721, 15749, 2, 10, 1, expected_idx(14))
  call init_index(INDEX_REC_LEN, 189425, 0, 37, 109, 143, 166, 4721, 15860, 2, 10, 1, expected_idx(15))
  call init_index(INDEX_REC_LEN, 205285, 0, 37, 109, 143, 166, 4721, 12978, 2, 10, 1, expected_idx(16))
  call init_index(INDEX_REC_LEN, 218263, 0, 37, 109, 143, 166, 4721, 18772, 2, 10, 1, expected_idx(17))
  call init_index(INDEX_REC_LEN, 237035, 0, 37, 109, 143, 166, 4721, 22188, 2, 10, 1, expected_idx(18))
  call init_index(INDEX_REC_LEN, 259223, 0, 37, 109, 143, 166, 4721, 22427, 2, 10, 1, expected_idx(19))

  print *, '   testing getg2ir() to generate index records from GRIB2 file.'
  
  ! Open a real GRIB2 file.
  call baopenr(LUGB, TEST_FILE_GDAS, iret)
  if (iret .ne. 0) stop 100

  ! Loop through the 19 messages in this test file, checking that the
  ! correct index information is generated by getg2ir() for each
  ! message.
  nlen_expected = INDEX_REC_LEN * NUM_MESSAGES
  do mnum = 0, 18
     call getg2ir(LUGB, BYTES_TO_SEARCH, BYTES_TO_SEARCH, mnum, cbuf, nlen, nnum, nmess, iret)
     !print *, 'mnum, iret, nlen, nnum, nmess: ', mnum, iret, nlen, nnum, nmess
     if (iret .ne. 0) stop 101
     if (nlen .ne. nlen_expected .or. nnum .ne. NUM_MESSAGES - mnum .or. nmess .ne. NUM_MESSAGES) stop 102
     nlen_expected = nlen_expected - INDEX_REC_LEN

     ! Parse the index record into special type.
     call parse_cbuf(cbuf, idx)
     !call print_index(idx)

     ! Is this what we expected?
     if (cmp_idx(idx, expected_idx(mnum + 1)) .ne. 0) stop 300
     
     ! Free memory.
     deallocate(cbuf)
  end do

  ! Close the GRIB2 file.
  call baclose(LUGB, iret)
  if (iret .ne. 0) stop 199
  
  print *, '   ok.'
  print *, '   testing getg2i() to read index records from an index file.'

  ! Open the index file, generated with the utility grb2index.
  call baopenr(LUGI, TEST_FILE_GDAS_INDEX, iret)
  if (iret .ne. 0) stop 3

  ! Check that this is an index file, and read it into buffer cbuf.
  call getg2i(LUGI, cbuf, nlen, nnum, iret)
  if (iret .ne. 0) stop 4
  if (nlen .ne. INDEX_REC_LEN * NUM_MESSAGES .or. nnum .ne. NUM_MESSAGES) stop 5

  ! Loop through each of the 19 index records, making sure they match
  ! the the values we expect.
  do mnum = 0, 18
     ! Parse the index record into special type.
     call parse_cbuf(cbuf(mnum * INDEX_REC_LEN + 1:), idx)
     !call print_index(idx)

     ! Is this what we expected?
     if (cmp_idx(idx, expected_idx(mnum + 1)) .ne. 0) stop 300
  end do

  ! Feee memory.
  deallocate(cbuf)

  ! Close the file.
  call baclose(LUGI, iret)
  if (iret .ne. 0) stop 50

  print *, '   ok.'
  print *, 'SUCCESS!...'
end program test_getg2ir_gdas


