NCEPLIBS-g2: gf_free.F90 File Reference
gf_free.F90 File Reference
Frees memory in derived type grib_mod::gribfield.
Functions/Subroutines
subroutine gf_free (gfld)
Free memory that was used to store array values in derived type grib_mod::gribfield.
Detailed Description
Frees memory in derived type grib_mod::gribfield.
Author
Stephen Gilbert
Date
2000-05-26
Definition in file gf_free.F90.
Function/Subroutine Documentation
gf_free()
subroutine gf_free (type(gribfield) gfld)
Free memory that was used to store array values in derived type grib_mod::gribfield.
Parameters
gfld derived type grib_mod::gribfield.
Author
Stephen Gilbert
Date
2000-05-26
Definition at line 11 of file gf_free.F90.
Referenced by getgb2(), getgb2p(), and gf_getfld().