# This is a GitHub actions workflow for NCEPLIBS-g2.
#
# This builds and tests, then builds and tests the grib_util develop
# branch.
#
# Ed Hartnett, 5/25/23
name: grib_utils 
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  grib_utils:
    runs-on: ubuntu-latest
    env:
      FC: gfortran
      CC: gcc

    strategy:
      fail-fast: true
      matrix:
        grib_util-branch: [develop, v1.2.4]

    steps:

    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libpng-dev zlib1g-dev libjpeg-dev

    - name: cache-jasper
      id: cache-jasper
      uses: actions/cache@v2
      with:
        path: ~/jasper
        key: jasper-${{ runner.os }}-3.0.3

    - name: checkout-jasper
      if: steps.cache-jasper.outputs.cache-hit != 'true'    
      uses: actions/checkout@v2
      with:
        repository: jasper-software/jasper
        path: jasper
        ref: version-3.0.3

    - name: build-jasper
      if: steps.cache-jasper.outputs.cache-hit != 'true'
      run: |
        cd jasper
        mkdir build-jasper && cd build-jasper
        cmake .. -DCMAKE_INSTALL_PREFIX=~/jasper
        make -j2
        make install

    - name: checkout-bacio
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-bacio
        path: bacio
        ref: develop

    - name: build-bacio
      run: |
        cd bacio
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/bacio
        make -j2
        make install
        
    - name: checkout-w3emc
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-w3emc
        path: w3emc
        ref: develop

    - name: cache-sp
      id: cache-sp
      uses: actions/cache@v2
      with:
        path: ~/sp
        key: sp-developer-${{ runner.os }}-2.3.3

    - name: checkout-sp
      if: steps.cache-sp.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-sp
        path: sp
        ref: v2.3.3

    - name: build-sp
      if: steps.cache-sp.outputs.cache-hit != 'true'
      run: |
        cd sp
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/sp
        make -j2
        make install
          
    - name: checkout-ip
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-ip
        path: ip
        ref: v3.3.3

    - name: build-ip
      run: |
        cd ip
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/ip -DCMAKE_PREFIX_PATH=~/sp
        make -j2
        make install
          
    - name: checkout-g2c
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-g2c
        path: g2c
        ref: develop

    - name: build-g2c
      run: |
        cd g2c
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=~/g2c -DCMAKE_PREFIX_PATH="~/jasper" ..
        make -j2
        make install
                 
    - name: build-w3emc
      run: |
        cd w3emc
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH=~/bacio -DCMAKE_INSTALL_PREFIX=~/w3emc -DBUILD_WITH_BUFR=OFF ..
        make -j2
        make install
        
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: g2

    - name:  build
      run: |
        set -x
        cd g2
        mkdir build
        cd build
        cmake -DJasper_ROOT=~/jasper -DCMAKE_PREFIX_PATH="~/bacio;~/w3emc" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=~/g2 ..
        make -j2 VERBOSE=1
        make install

    - name: test
      run: |
        cd $GITHUB_WORKSPACE/g2/build
        ctest --verbose --output-on-failure --rerun-failed

    - name: checkout-grib_utils
      uses: actions/checkout@v2
      with: 
        repository: NOAA-EMC/NCEPLIBS-grib_util
        path: grib_utils
        ref: ${{ matrix.grib_util-branch }}
        
    - name: build-grib_utils
      run: |
        cd grib_utils
        mkdir build && cd build
        ls -l ~/jasper/lib
        export LD_LIBRARY_PATH=/home/runner/jasper/lib
        export PATH="~/g2c/bin:$PATH"
        cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH="~/bacio;~/jasper;~/sp;~/ip;~/w3emc;~/g2;~/g2c" ..
        make -j2 VERBOSE=1
        ctest --output-on-failure --rerun-failed --verbose



