# This is a GitHub actions workflow for NCEPLIBS-g2.
#
# This builds and tests, then builds and tests the grib_util develop
# branch.
#
# Ed Hartnett, 5/25/23
name: grib_utils 
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  grib_utils:
    runs-on: ubuntu-latest
    env:
      FC: gfortran
      CC: gcc

    strategy:
      fail-fast: true

    steps:

    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libpng-dev zlib1g-dev libjpeg-dev

    - name: checkout-bacio
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-bacio
        path: bacio
        ref: develop

    - name: build-bacio
      run: |
        cd bacio
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/bacio
        make -j2
        make install
        
    - name: checkout-w3emc
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-w3emc
        path: w3emc
        ref: develop

    - name: build-w3emc
      run: |
        cd w3emc
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH=~/bacio -DCMAKE_INSTALL_PREFIX=~/w3emc -DBUILD_WITH_BUFR=OFF ..
        make -j2
        make install
        
    - name: cache-jasper
      id: cache-jasper
      uses: actions/cache@v2
      with:
        path: ~/Jasper
        key: jasper-${{ runner.os }}-3.0.3

    - name: checkout-jasper
      if: steps.cache-jasper.outputs.cache-hit != 'true'    
      uses: actions/checkout@v2
      with:
        repository: jasper-software/jasper
        path: jasper
        ref: version-3.0.3

    - name: build-jasper
      if: steps.cache-jasper.outputs.cache-hit != 'true'
      run: |
        cd jasper
        mkdir build-jasper && cd build-jasper
        cmake .. -DCMAKE_INSTALL_PREFIX=~/Jasper
        make -j2
        make install

    - name: checkout
      uses: actions/checkout@v2
      with:
        path: g2

    - name:  build
      run: |
        set -x
        cd g2
        mkdir build
        cd build
        cmake -DJasper_ROOT=~/Jasper -DCMAKE_PREFIX_PATH="~/bacio;~/w3emc" -DCMAKE_BUILD_TYPE=Debug ..
        make -j2 VERBOSE=1

    - name: test
      run: |
        cd $GITHUB_WORKSPACE/g2/build
        ctest --verbose --output-on-failure --rerun-failed



