name: Linux_versions
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FC: gfortran
      CC: gcc

    strategy:
      fail-fast: true
      matrix:
        jasper-version: [2.0.33, 3.0.3]
        bacio-version: [2.4.1, 2.5.0]

    steps:

    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libpng-dev zlib1g-dev libjpeg-dev 

    - name: checkout-bacio
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-bacio
        path: bacio
        ref: v${{ matrix.bacio-version }}

    - name: build-bacio
      run: |
        cd bacio
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/bacio
        make -j2
        make install
    - name: checkout-w3emc
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-w3emc
        path: w3emc
        ref: v2.9.2

    - name: build-w3emc
      run: |
        cd w3emc
        mkdir build
        cd build
        cmake .. -DCMAKE_PREFIX_PATH=~/bacio -DCMAKE_INSTALL_PREFIX=~/w3emc
        make -j2
        make install
    - name: checkout-jasper
      uses: actions/checkout@v2
      with:
        repository: jasper-software/jasper
        path: jasper
        ref: version-${{ matrix.jasper-version }}

    - name: cache-jasper
      id: cache-jasper
      uses: actions/cache@v2
      with:
        path: ~/Jasper
        key: jasper-${{ runner.os }}-${{ hashFiles('jasper/VERSION') }}

    - name: build-jasper
      if: steps.cache-jasper.outputs.cache-hit != 'true'
      run: |
        cd jasper
        mkdir build-jasper && cd build-jasper
        cmake .. -DCMAKE_INSTALL_PREFIX=~/Jasper
        make -j2
        make install

    - name: checkout-g2c
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-g2c
        path: g2c
        ref: develop

    - name: build-g2c
      run: |
        cd g2c
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/g2c -DJasper_ROOT=~/Jasper
        make -j2
        make install
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: g2

    - name:  build
      run: |
        set -x
        cd g2
        mkdir build
        cd build
        cmake .. -DJasper_ROOT=~/Jasper -DCMAKE_PREFIX_PATH="~/g2c;~/bacio;~/w3emc"
        make -j2 VERBOSE=1

    - name: test
      run: |
        cd $GITHUB_WORKSPACE/g2/build
        export LD_LIBRARY_PATH=/home/runner/Jasper/lib
        ctest --verbose --output-on-failure


