name: macOS Build
on: [push, pull_request]

jobs:
  macOS-build:
    runs-on: macos-latest
    env:
      FC: gfortran-9
      CC: gcc-9

    steps:
    - name: install-dependencies
      run: |
        brew update
        brew install openjpeg libpng

    - name: checkout-bacio
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-bacio
        path: bacio
        ref: develop

    - name: build-bacio
      run: |
        cd bacio
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/bacio
        make -j2
        make install
    - name: checkout-jasper
      uses: actions/checkout@v2
      with:
        repository: jasper-software/jasper
        path: jasper
        ref: version-2.0.33

    - name: cache-jasper
      id: cache-jasper
      uses: actions/cache@v2
      with:
        path: ~/Jasper
        key: jasper-${{ runner.os }}-${{ hashFiles('jasper/VERSION') }}

    - name: build-jasper
      if: steps.cache-jasper.outputs.cache-hit != 'true'
      run: |
        cd jasper
        mkdir build-jasper && cd build-jasper
        cmake .. -DCMAKE_INSTALL_PREFIX=~/Jasper
        make -j2
        make install

    - name: checkout
      uses: actions/checkout@v2
      with:
        path: g2

    - name: build
      run: |
        cd g2
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH="~/Jasper;~/bacio" ..
        make -j2

    - name: test
      run: |
        cd $GITHUB_WORKSPACE/g2/build
        ctest  --output-on-failure
